# .gitlab-ci.yml
---
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  GIT_DEPTH: 0
  GIT_SUBMODULE_STRATEGY: recursive
  SERVICE: mms
  DMC_NAME: $SERVICE-mgmt-dmc

include:
  - local: .gitlab/ci/*

# .gitlab/ci/login.yml
---
.docker_login:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# .gitlab/ci/docker_management_container.yml
---
stages:
  - docker_management_container

include:
  remote: https://raw.githubusercontent.com/T-Systems-MMS/docker-management-container/master/examples/pipeline/gitlab-ci/dmc.yml

build_dmc:
  variables:
    DMC_NAME: $DMC_NAME
