---
name: linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
        env:
          SHELLCHECK_OPTS: -e SC1003
